#!/bin/bash

# define the location of the project
export PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# start the Python virtual environment
source ~/.venvs/amsat_txrx_ic/bin/activate